org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.aapt2.keepRawResources=true
# 禁用 aapt2 daemon，让其每次 fork 新进程（这样 wrapper 生效）
android.aapt2.useDaemonMode=false
android.aapt2FromMavenOverride=/opt/aapt2-custom/aapt2
